### ISSUE TITLE
Right Click with empty hand crashes game

### ISSUE THREAD

**Issue by Henrysssong** [MehVahdJukaar/Dummy_1.18#5]
Right click with empty hand will crash the whole server.

I didn't save error log but this can be easily reproduced. Simply right click on a target dummy with empty hand.

**Comment by Henrysssong** [comment]
Actually crash reports are saved. Here is the relevant part.

```
Description: Unexpected error

java.lang.NoSuchMethodError: 'boolean net.mehvahdjukaar.moonlight.api.platform.ForgeHelper.canEquipItem(net.minecraft.class_1309, net.minecraft.class_1799, net.minecraft.class_1304)'
	at net.mehvahdjukaar.dummmmmmy.common.TargetDummyEntity.method_5664(TargetDummyEntity.java:160)
	at net.minecraft.class_636.method_2917(class_636.java:433)
	at net.minecraft.class_310.method_1583(class_310.java:1731)
	at net.minecraft.class_310.method_1508(class_310.java:2002)
	at net.minecraft.class_310.method_1574(class_310.java:1829)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.mehvahdjukaar.dummmmmmy.common.TargetDummyEntity.method_5664(TargetDummyEntity.java:160)
	at net.minecraft.class_636.method_2917(class_636.java:433)
	at net.minecraft.class_310.method_1583(class_310.java:1731)
	at net.minecraft.class_310.method_1508(class_310.java:2002)
Mixins in Stacktrace: None found
```

**Comment by MehVahdJukaar** [comment]
Update moonlight
